# Generated by Django 3.2 on 2022-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_crud_vitsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='joke',
            field=models.CharField(default='', max_length=300),
        ),
    ]
