# Generated by Django 3.2 on 2022-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_crud_joke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='joke',
            field=models.TextField(default='', max_length=300),
        ),
    ]
