# Generated by Django 3.2 on 2022-05-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_crud_joke'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='origin',
            field=models.IntegerField(default=1900),
        ),
    ]
